defaults:
  - _self_
  - agent: ppo

seeds: 
# - 0
# - 1
# - 2
# - 42
- 3407 # https://arxiv.org/abs/2109.08203

tag: null
# env_name: LunarLanderContinuous-v2
# vec_envs: 16
env_name: Ligent
vec_envs: 1
nstep: 1

train:
  nstep: ${nstep}
  vec_envs: ${vec_envs}
  timesteps: 3_000_000
  batch_size: 512
  plot_interval: 1024
  eval_interval: 1024
  eval_episodes: 5
  ppo_update_interval: ${buffer.capacity}

buffer:
  _target_: buffer.PPOReplayBuffer
  capacity: 4096 #16384
  state_img_size: [56, 56, 3]
  state_text_size: 520
  action_size: ${action_decoder.action_used_dims}
  # use_per: False
  # use_ppo: True
  # nstep: 1
  gamma: ${agent.gamma}
  # per_alpha: 0.7
  # per_beta: 0.4
  # per_eps: 0.01
  gae_lambda: 0.95
  num_envs: ${vec_envs}

action_decoder:
  _target_: agent.action_decoder.ActionDecoder
  decode_idx: 6
  action_used_dims: 7
  action_env_dims: 520
  

feature_net:
  _target_: agent.features.FeatureFusion
  hidden_depth: 2
  text_input_size: ${buffer.state_text_size}
  text_hidden_size: 10
  img_input_size: ${buffer.state_img_size}
  img_hidden_size: 128

hydra:
  job:
    chdir: true
  run:
    dir: ./runs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.override_dirname}
